### ISSUE TITLE
Adjust repository settings for default branch

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ruby-style-guide#5]
@nning (or some other member of @ontohub/owners) Could you please adjust the repository in such a way that pull-requests default to _our_ master branch and not on `bbatsov/rub-style-guide` master?

**Comment by nning** [comment]
The default branch of our fork is already our master. There's no extra option to change the default branch to create pull requests on. The fork parent's default branch seems to be automatically assumed, here.

**Comment by 0robustus1** [comment]
Mhm, okay in this case we'll probably just have to live with it, i guess.
